# 网站基本信息
title: 小蓝的笔记本
description: 总会有些意想不到的东西
# url: "https://your-username.github.io"   # 你的网站地址，GitHub Pages 域名或自定义域名
# baseurl: ""                             # 如果是仓库页面，填仓库名，比如 "/repo-name"，否则留空


# 主题
# theme: minima  # 默认主题，支持目录和美观样式

# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
  # - jekyll-remote-theme # add this line to the plugins list if you already have one

# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one


theme: jekyll-theme-primer
plugins:
  - jekyll-optional-front-matter  # 允许无front-matter的文件


# 重要配置项
permalink: pretty
include:
  - "_pages"
  - "笔记库/**/*"  # 包含所有深层Markdown文件
  
# KaTeX配置标记（可选）
katex:
  css: https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
  js: 
    - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js



# 语言和时区
locale: zh-CN
timezone: Asia/Shanghai


# 其他配置
markdown: kramdown
# collections:
  # mynotes:
    # output: true
    # permalink: /mynotes/:name.html
highlighter: rouge
encoding: utf-8


sass:
  sass_dir: _sass
  style: compressed


# 未来可拓展的配置项
author:
  name: 蓝天龙
  email: m.lantianlong@qq.com
